// Just enough of a zip writer to build Apple Health fixtures.
//
// The point of a fixture is to be the thing you are testing against, not a
// convenient stand-in for it, so these are real archives: real deflate streams,
// a real central directory, and - because a long Apple Health history needs it -
// real zip64 size fields. Written here rather than generated by a script in
// another language so that `npm test` needs nothing installed.

const CRC = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(bytes) {
  let c = ~0;
  for (let i = 0; i < bytes.length; i++) c = CRC[(c ^ bytes[i]) & 0xff] ^ (c >>> 8);
  return (~c) >>> 0;
}

async function deflateRaw(bytes) {
  const s = new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate-raw'));
  const parts = [];
  for await (const chunk of s) parts.push(chunk);
  return new Uint8Array(await new Blob(parts).arrayBuffer());
}

const bytes = (...n) => new Uint8Array(n);
const u16 = (n) => bytes(n & 0xff, (n >>> 8) & 0xff);
const u32 = (n) => bytes(n & 0xff, (n >>> 8) & 0xff, (n >>> 16) & 0xff, (n >>> 24) & 0xff);
const u64 = (n) => { const b = new Uint8Array(8); new DataView(b.buffer).setBigUint64(0, BigInt(n), true); return b; };
const join = (...parts) => {
  const total = parts.reduce((a, p) => a + p.length, 0);
  const out = new Uint8Array(total);
  let at = 0;
  for (const p of parts) { out.set(p, at); at += p.length }
  return out;
};

/**
 * Build an archive.
 *
 * `entries` is [{ name, data, store?, zip64?, encrypted? }]. `store` writes the
 * entry uncompressed, `zip64` parks sentinels in the 32-bit fields and puts the
 * real sizes in an extra field, and `encrypted` flips the flag bit so the reader
 * has something to refuse.
 */
export async function makeZip(entries) {
  const SENT = 0xffffffff;
  const locals = [];
  const central = [];
  let offset = 0;

  for (const e of entries) {
    const raw = typeof e.data === 'string' ? new TextEncoder().encode(e.data) : e.data;
    const body = e.store ? raw : await deflateRaw(raw);
    const name = new TextEncoder().encode(e.name);
    const flags = e.encrypted ? 1 : 0;
    const method = e.store ? 0 : 8;
    const crc = crc32(raw);

    // Zip64: the local header carries a 20-byte extra field, and the central
    // one carries only the fields that overflowed - which is the part a reader
    // gets wrong if it assumes all three are always present.
    const localExtra = e.zip64 ? join(u16(1), u16(16), u64(raw.length), u64(body.length)) : bytes();
    const head = join(u32(0x04034b50), u16(e.zip64 ? 45 : 20), u16(flags), u16(method), u16(0), u16(0),
      u32(crc), u32(e.zip64 ? SENT : body.length), u32(e.zip64 ? SENT : raw.length),
      u16(name.length), u16(localExtra.length), name, localExtra);
    locals.push(head, body);

    const cdExtra = e.zip64 ? join(u16(1), u16(24), u64(raw.length), u64(body.length), u64(offset)) : bytes();
    central.push(join(u32(0x02014b50), u16(20), u16(e.zip64 ? 45 : 20), u16(flags), u16(method), u16(0), u16(0),
      u32(crc), u32(e.zip64 ? SENT : body.length), u32(e.zip64 ? SENT : raw.length),
      u16(name.length), u16(cdExtra.length), u16(0), u16(0), u16(0), u32(0),
      u32(e.zip64 ? SENT : offset), name, cdExtra));

    offset += head.length + body.length;
  }

  const cd = join(...central);
  const anyZip64 = entries.some(e => e.zip64);
  let tail = join(u32(0x06054b50), u16(0), u16(0), u16(entries.length), u16(entries.length),
    u32(cd.length), u32(anyZip64 ? SENT : offset), u16(0));

  if (anyZip64) {
    // A zip64 archive says so twice: a 56-byte record, and a locator pointing at
    // it that sits immediately before the 32-bit record.
    const at = offset + cd.length;
    const rec = join(u32(0x06064b50), u64(44), u16(45), u16(45), u32(0), u32(0),
      u64(entries.length), u64(entries.length), u64(cd.length), u64(offset));
    const loc = join(u32(0x07064b50), u32(0), u64(at), u32(1));
    tail = join(rec, loc, tail);
  }

  return join(join(...locals), cd, tail);
}

/** A zip with a trailing comment, so the reader has to search for the EOCD. */
export function withComment(zip, comment) {
  const c = new TextEncoder().encode(comment);
  const out = new Uint8Array(zip.length + c.length);
  out.set(zip);
  out.set(c, zip.length);
  // The comment length field is the last two bytes of the EOCD record.
  new DataView(out.buffer).setUint16(zip.length - 2, c.length, true);
  return out;
}
